# Generated by Django 5.1.2 on 2024-10-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus_code",
                    models.CharField(
                        choices=[
                            ("A", "Seniors (Kurmannapalem)"),
                            ("B", "Juniors (Scindia)"),
                            ("C", "Juniors (Srikakulam)"),
                            ("D", "Seniors (Srikakulam)"),
                            ("E", "Juniors (Bobbili)"),
                            ("F", "Seniors (Saluru)"),
                            ("G", "Seniors (NAD - Karasa)"),
                            ("H", "Juniors (Siripuram - VSP)"),
                            ("I", "Seniors (NAD - NSTL Gate)"),
                            ("J", "Juniors (NAD - NSTL)"),
                            ("K", "Seniors (Town Kotha Road)"),
                            ("L", "Seniors (NAD - NSTL)"),
                            ("M", "Juniors/Seniors (Sabbavaram)"),
                            ("N", "Seniors (NAD - Baji Jn..)"),
                            ("O", "Juniors/Seniors (NAD - Baji Jn..)"),
                            ("P", "Seniors (Dabagardens)"),
                            ("Q", "Seniors (Denkada)"),
                            ("R", "Juniors (Nellimarla)"),
                            ("S", "Seniors (L Kota)"),
                            ("T", "Juniors (Ayyannapeta)"),
                            ("U", "Seniors (Cheepurupalli)"),
                            ("V", "Seniors (Ayyannapeta)"),
                            ("W", "Seniors (Poolbhag)"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
                ("stop_name", models.CharField(max_length=100)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_time", models.TimeField()),
            ],
        ),
    ]
