# Generated by Django 5.1.2 on 2024-10-28 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus", "0003_busnames_feedback_delete_busroute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="condition",
        ),
        migrations.AddField(
            model_name="feedback",
            name="Buscondition",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
